[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Pengalihan automatik (301 Redirect) dari .html ke Clean URL
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
